Terraform Destory command updated in the workflow to pass ssh_key automatically

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -46,7 +46,7 @@ jobs:
 
       - name: Terraform Destroy (before re-creation)
         id: destroy_before_create
-        run: terraform destroy -auto-approve || true # Allow destroy to fail if no resources exist
+        run: terraform destroy -auto-approve -var "key_name=${{ secrets.SSH_KEY_NAME }}" || true # Allow destroy to fail if no resources exist
         working-directory: ./terraform
 
       - name: Terraform Apply
